---
  inherit_gem:
    dox-style:
    - ".rubocop.yml"

  Env/OutsideConfig:
    Exclude:
      - "./tasks/ci.rake"

  Env/UndefinedVar:
    Exclude:
      - "./tasks/ci.rake"

  Env/UseFetch:
    Exclude:
      - "./bin/*"

  Metrics/BlockLength:
    Exclude:
      - "./**/*_spec*.rb"
      - "./*.gemspec"
      - "./spec/*_helper*.rb"
      - "./tasks/ci.rake"
      - "Gemfile"

  Metrics/ModuleLength:
    Exclude:
      - "./**/*_spec*.rb"

  Metrics/AbcSize:
    Enabled: false

  Metrics/CyclomaticComplexity:
    Enabled: false

  Metrics/MethodLength:
    Enabled: false

  Metrics/PerceivedComplexity:
    Enabled: false

  Metrics/BlockLength:
    Enabled: false

  Lint/DuplicateMethods:
    Enabled: false

  Layout/LineLength:
    Enabled: false

  RSpec/FilePath:
    Enabled: false

  RSpec/BeforeAfterAll:
    Enabled: false
